### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by bbbenji** [Lochneska/t470s-hackintosh#1]
Thanks for sharing! Could you please add your machine specs to the README? Also, any plans on upgrading to Sonoma?

**Comment by Lochneska** [comment]
Hi! Thanks for the suggestion, I’ve added them into the README. :) 

And yeah, eventually I will, but for now I won’t, as I don’t see any features I’d be excited for and I don’t want to deal with possible bugs either, since it is an early release for now. :)
